name: RELEASE

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-electron:
    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v6.2.0

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v6.2.0
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run make

      - name: Upload artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v6.0.0
        with:
          name: macos-artifacts
          path: |
            out/make/**/*.dmg
            out/make/**/*.zip

      - name: Upload artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v6.0.0
        with:
          name: linux-artifacts
          path: |
            out/make/**/*.deb
            out/make/**/*.rpm

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v6.0.0
        with:
          name: windows-artifacts
          path: |
            out/make/**/*.exe
            out/make/**/*.msi

  create-draft-release:
    needs: [build-electron]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v7.0.0
        with:
          name: macos-artifacts
          path: artifacts/macos/

      - name: Download Linux artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v7.0.0
        with:
          name: linux-artifacts
          path: artifacts/linux/

      - name: Download Windows artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v7.0.0
        with:
          name: windows-artifacts
          path: artifacts/windows/

      - name: Create Draft Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          name: ${{ github.ref_name }}
          draft: true
          files: |
            artifacts/**/*
